name: crunchyroll_calendar
description: "Ein inoffizieller Kalender für Anime-Veröffentlichungen auf Crunchyroll."
publish_to: 'none'
version: 0.9.5+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  table_calendar: ^3.2.0
  intl: ^0.20.2
  http: ^1.2.0
  html: ^0.15.4
  cached_network_image: ^3.3.1
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.0
  translator: ^1.0.0
  workmanager: ^0.9.0+3
  flutter_local_notifications: ^17.2.3
  sqflite: ^2.4.2
  path: ^1.9.1
  path_provider: ^2.1.5
  timezone: ^0.9.4
  file_picker: ^8.1.6
  share_plus: ^10.1.3
  device_info_plus: ^11.0.0
  crypto: ^3.0.3
  package_info_plus: ^8.1.2
  ota_update: ^7.1.0
  sqflite_common_ffi: ^2.3.0
  sqlite3_flutter_libs: ^0.5.24
  window_manager: ^0.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
